### ISSUE TITLE
All default vallues in rules.xml should be split by "," not by ", "

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#107]
description of problem is at #103 .

All other cases need to be fixed, UT to prevent this should be written.

**Comment by romani** [comment]
default values are fixed, UT still need to be created.

**Comment by rnveach** [comment]
@romani UT was going to be created in Issue #91 as we are waiting on changes in CS to recognize all types.
We still can't recognize most custom enumerations and they will all currently show up as strings.
