### ISSUE TITLE
checkstyle:com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocContentLocationCheck has incorrect (lowercase instead of uppercase) default value

### ISSUE THREAD

**Issue by alixwar** [checkstyle/sonar-checkstyle#328]
Sonar version: 8.3
Checkstyle sonar plugin version: 8.35

Steps to reproduce or description of problem:
See description in SonarQube for rule "checkstyle:com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocContentLocationCheck":

> Parameters
> location | Specify the policy on placement of the Javadoc content.
>Default Value: second_line

When invoking the web service API and trying to set the value of location using "second_line" (note: Default!) SonarQube results in a HTTP 404 (bad request):

> {"errors":[{"msg":"Value 'second_line' must be one of : FIRST_LINE, SECOND_LINE."}]}

Solution: Change the default value of the rule to "SECOND_LINE"

**Comment by alixwar** [comment]
Same problem with checkstyle:com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck

**Comment by alixwar** [comment]
... and checkstyle:com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyForIteratorPadCheck

**Comment by alixwar** [comment]
.... and checkstyle:com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyForInitializerPadCheck

**Comment by alixwar** [comment]
... and checkstyle:com.puppycrawl.tools.checkstyle.checks.javadoc.AtclauseOrderCheck

**Comment by muhlba91** [comment]
@alixwar thanks for raising this issue. we have tested default values in 8.35 as well but through the UI (selecting the rule and click enable without filling any data) which worked for us.
in fact, i believe this stems from our documentation not reflecting the proper default value‘s capitalization which we „copy“ over from the main CS project‘s documentation, resulting in the wrong value displayed although, if left blank, the check instantiates properly.
would you mind verifying that enabling the check through the UI without filled data works for you as well?

it also sounds like you are enabling the rules through an API call with default values retrieved by another previous API call? are you be able to post a script for this procedure?

@gaurabdg please verify those checks and conpare with documentation/metadata generated and used by sonar here?

@romani i think this issue should be applied to the main CS project where the documentation defers from the actual and correct default values‘ capitalization.

**Comment by alixwar** [comment]
@muhlba91 I'm in the middle of trying to fix this on my web service integration. Is it helpful if I provide more rules with this problem meanwhile?

**Comment by muhlba91** [comment]
@alixwar thanks. 👍 
yes, it is very helpful as we gather data about which check‘s documentation is wrong, allowing us to perform explicit tests on them.

**Comment by alixwar** [comment]
> it also sounds like you are enabling the rules through an API call with default values retrieved by another previous API call? are you be able to post a script for this procedure?

I'm invoking this REST API: "qualityprofiles/activate_rule"

with these fields set: "key", "rule" "severity"
The rest of the parameters are optional so this should be a valid request. Implicitly, I guess, SonarQube tries to set the default values on the rest of the fields.

**Comment by alixwar** [comment]
I have great difficulties with rule checkstyle:com.puppycrawl.tools.checkstyle.checks.javadoc.AtclauseOrderCheck

No input seems to be OK (I tried even through the UI):

{"errors":[{"msg":"Value 'CLASS_DEF' must be one of : ."}]}

Could you please provide the correct default values for this rule?

**Comment by alixwar** [comment]
Interesting... Even in the Checkstyle project this default is with lower case:

https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocContentLocationCheck.html

Could SonarQube somehow be the culprit?

**Comment by alixwar** [comment]
... and checkstyle:com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck

**Comment by romani** [comment]
@gaurabdg , here is list of Checks that fails for the same problem, tokens are defined in non base property. 
```
~/java/github/checkstyle/checkstyle [master|✔] 
$ ag -B 5 "TokenUtil.getTokenId"
....
src/main/java/com/puppycrawl/tools/checkstyle/checks/DescendantTokenCheck.java
...
494-    public void setLimitedTokens(String... limitedTokensParam) {
495-        limitedTokens = new int[limitedTokensParam.length];
496-
497-        int maxToken = 0;
498-        for (int i = 0; i < limitedTokensParam.length; i++) {
499:            limitedTokens[i] = TokenUtil.getTokenId(limitedTokensParam[i]);

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MultipleStringLiteralsCheck.java
...
192-    public final void setIgnoreOccurrenceContext(String... strRep) {
193-        ignoreOccurrenceContext.clear();
194-        for (final String s : strRep) {
195:            final int type = TokenUtil.getTokenId(s);

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java
...
553-    public void setConstantWaiverParentToken(String... tokens) {
554-        constantWaiverParentToken = new int[tokens.length];
555-        for (int i = 0; i < tokens.length; i++) {
556:            constantWaiverParentToken[i] = TokenUtil.getTokenId(tokens[i]);

src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/IllegalTypeCheck.java
...
825-    public void setMemberModifiers(String modifiers) {
826-        final List<Integer> modifiersList = new ArrayList<>();
827-        for (String modifier : modifiers.split(",")) {
828:            modifiersList.add(TokenUtil.getTokenId(modifier.trim()));

src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/AtclauseOrderCheck.java
...
161-    public void setTarget(String... targets) {
162-        final List<Integer> customTarget = new ArrayList<>();
163-        for (String temp : targets) {
164:            customTarget.add(TokenUtil.getTokenId(temp.trim()));
```

I see that they have proper type and validationType in javadoc 
https://github.com/checkstyle/checkstyle/blob/cf329667bd119a6e49af6e72b5bb7b401281abdb/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/MagicNumberCheck.java#L81-L84

**Comment by romani** [comment]
We have one more problem.
We mixed javadocTokens and javaTokens under the same validation type - `tokenSet` it is not correct.
https://github.com/checkstyle/checkstyle/blob/cf329667bd119a6e49af6e72b5bb7b401281abdb/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java#L40-L42
We need to make new validation type `javadocTokenSet` to be exact on type and do not depend on base class of Check.

**Comment by gaurabdg** [comment]
> We have one more problem.
> We mixed javadocTokens and javaTokens under the same validation type - `tokenSet` it is not correct.
> https://github.com/checkstyle/checkstyle/blob/cf329667bd119a6e49af6e72b5bb7b401281abdb/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/NonEmptyAtclauseDescriptionCheck.java#L40-L42
> We need to make new validation type `javadocTokenSet` to be exact on type and do not depend on base class of Check.
> Fortunately we have no usage of special properties for such tokens in our code, but if it appear it will be `javadocTokenSet`

@romani It doesnt matter if we keep it `tokenSet` because the utility function implemented in plugin, to get modifiable tokens determines whether to fetch tokens/javadoc tokens.

**Comment by romani** [comment]
> function implemented in plugin to get modifiable tokens, determines whether to fetch tokens/javadoc tokens.

Whole idea of metadata project is to let plugin trust content and and easily understand types and values.
Please create issue on this, we need to change it before metadata become popular in other extensions.

**Comment by romani** [comment]
Fix is merged

**Comment by alixwar** [comment]
I'm still seeing this in SonarQube 8.5.1 with version 8.37 of the Checkstyle plugin.

Rule: checkstyle:com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyForInitializerPadCheck

"errors":[{"msg":"Value 'NOSPACE' must be one of : nospace, space."}]}

**Comment by romani** [comment]
@alixwar , please create new issue
