### ISSUE TITLE
upgrade to checkstyle 8.36.1

### ISSUE THREAD

**Issue by romani** [checkstyle/sonar-checkstyle#331]
https://checkstyle.org/releasenotes.html#Release_8.36.1

**Comment by muhlba91** [comment]
@romani @gaurabdg when installing the new version on SQ, I see the following deviation.

CS 8.35:
<img width="1010" alt="Screenshot 2020-09-13 at 1 37 57 PM" src="https://user-images.githubusercontent.com/653739/93017145-af346e00-f5c6-11ea-84b5-d644d02efa23.png">

CS 8.36.1:
<img width="1032" alt="Screenshot 2020-09-13 at 1 39 35 PM" src="https://user-images.githubusercontent.com/653739/93017153-b9566c80-f5c6-11ea-9b85-808f0f2a2f35.png">

Almost all rules/checks (except for `SuppressWarningsFilter`) are template rules now.

@romani is this an expected change from CS side?
I understand it logically that I might enable different variations of checks when I have at least 1 parameter which is non-enum like. Examples would be `AnnotationLocationCheck` or `AvoidStarImportCheck`.
However, for others (e.g. `AvoidInlineConditionalsCheck`) they do not even have one parameter and, again others (e.g. `AnnotationOnSameLineCheck`) have only the tokens which is an enum list.
There are also other checks with exactly one parameter (true/false like `AvoidNestedBlocksCheck`) where this doesn't make sense to me.

Anyhow, if this is intended on CS side, I'll perform the release nevertheless.
Otherwise, @gaurabdg please investigate, create issue and fix. :)

**Comment by romani** [comment]
https://checkstyle.org/config_coding.html#AvoidInlineConditionals has no properties, it should not be template

https://checkstyle.org/config_annotation.html#AnnotationOnSameLine is not obvious. From first sight it not reasonable to make it template as only tokens are modifiable, but user might create two instances of Check to use different suppressions for them or use different message on violations.

**Comment by muhlba91** [comment]
i suspect this check resulting in wrong results: https://github.com/checkstyle/sonar-checkstyle/blob/master/src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java#L145

`getMethods()` also retrieves inherited methods to which e.g. `setTokens(...)` belongs. as all checks are inheriting from the base class `AbstractCheck` all of them will have a setter, and become a template.

`AvoidInlineConditionalsCheck` also inherits from this class, and becomes a template , although it doesn't use tokens, i presume?

interestingly, `SuppressWarningsFilter` is the only check/rule which extends a class that does not have any setter defined, and, therefore, is the only non-template rule/check in SQ.

the alternative to `getMethods()` can be `getDeclaredMethods()` but this will not retrieve the tokens and others as parameters to define a template rule upon. this would then not allow any check/rule to be a template like `AnnotationOnSameLine` which do not define any custom parameters apart from the base class ones.

ignoring `SuppressWarningsFilter` now, i see a potential fix in modifying this method to:
- use `getDeclaredMethods()` -> if this returns any setter, it can only be a template rule, i presume?
- otherwise, we would need to instantiate it and call `getAcceptableTokens()` -> if this list's size is greater than 1, we can also generate templates as we can have two checks with different tokens, i believe?

however, this will not solve `AvoidNestedBlocksCheck` as (1) would result in the boolean setter to be found, although (2) would clearly evaluate to false. those i'd see as corner-ish cases where we would need more intelligence on the type of setters and the combination of all parameters.
i can see an extension of custom properties to define such checks as non-templating rules though.

additionally, the previous idea ignores `SuppressWarningsFilter` for which we'd need to catch the exception of a method not being available (`getAvailableTokens()`) and evaluate those cases to non-templating rules by default if (1) clearly shows no defined setters.

@gaurabdg please take a closer look and verify/reject my investigations.
@gaurabdg @romani would such an evaluation of `isTemplateRule` be sufficient enough to produce sufficient improvement or did i oversee any case? would it be also necessary/make sense to introduce a custom property short-circuiting the evaluation?

**Comment by romani** [comment]
```
private boolean isTemplateRule(String checkName) {
        return Arrays.stream(getClass(checkName).getMethods())
                .anyMatch(CheckstyleMetadata::isSetter);
    }
```

Is too basic implementation, our bad to miss this during review.
 We should do this based on data from metada file. 
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/coding/AvoidInlineConditionalsCheck.xml - if no properties , it is not a template.

**Comment by romani** [comment]
@muhlba91 , please finalize testing and do release if all looks good.

fyi: #335
but better to not block testing of this issue.

**Comment by muhlba91** [comment]
tested and looking good in general BUT how do we handle breaking changes?

all rules that previously were (wrongly) rules and are now corrected to template rules will cause an exception - unfortunately, that exception only says cannot run checkstyle with no adequate information on which check causes the problem. i deleted all check and re-created template rules and it was good.

i increased from 4.34 to 8.35 with the introduction of metadata. would this be a good reason to say with 8.35/8.36 we increased the version and backwards compatibility is not provided anymore?

i‘d like to refrain from manually „fixing“ and wrongly asserting template rules as rules again as we need to fix it anyways. if not now, in the future we definitely have to introduce this breaking change once.

how did you handle breaking changes in the past?
what do you think @romani ?

**Comment by romani** [comment]
> all rules that previously were (wrongly) rules and are now corrected to template rules will cause an exception - unfortunately, that exception only says cannot run checkstyle with no adequate information on which check causes the problem. i deleted all check and re-created template rules and it was good.

this is huge problem.
We should not force whole world to redo their configs, especially if https://github.com/checkstyle/sonar-checkstyle/issues/2 is not fixed.
We did minor breaking changes only in past, or something that requires update for Sonar version, .... .

This damage is too painful.
 
What if we keep all existing rules metadata as is, it will recreate all rules as before, so no breaking changes. BUT we will create "duplicates" as templates for all Checks that become Templates but do have old meta as non-template. We can add ` Template` to name. 
So in UI it will looks like:
`Indentation`
`Indentation Template`

`Indentation` - will load from old metadata content, it is a rule.
`Indentation Template` - all docs are from new metadata, it is a template.

**Note:**
`IllegalIdentifierName` (check from 8.36) will be template from the beginning.
`NoClone` (old check) stay as rule as it does not change.

We have to keep old metadata files kind of forever.
Thirdparties (like sevntu) should deal with it as they want, keep compatibility or break it.

**Comment by gaurabdg** [comment]
@romani @muhlba91 But this would introduce duplicates:
`java.lang.IllegalArgumentException: The rule 'com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck' of repository 'checkstyle' is declared several times
`
Changing the key structure would bring in a lot of changes

**Comment by romani** [comment]
@gaurabdg , can we append to key suffix "template" it it is loaded from new metada ? So keys will be different, but instantiated classes the same

**Comment by muhlba91** [comment]
will close this issue as the release will be skipped in favour of #345 which fixes further regressions
